name: Android CI

on:
  push:
    branches: [ 'upgrade/target-sdk-29' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 29
        build-tools: '29.0.3'

    - name: Give execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apks
        path: app/build/outputs/**/*.apk

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: build/reports/**/*.txt